#**********************************************************
# Makefile for irc bot (based on orbitz bot)
# Laughing man IRC library uses orbitz
#
# Date: 3/1/2008
# Author: Berlin Brown
#
#**********************************************************

TOPDIR := $(shell pwd)
DATE   = $(shell date +%Y%m%d)

VERSION     = 0.0.1

SED   = $(shell which sed)

all: clean

clean:
	-rm -Rvf *.pyc

# End of the file 
