#!/bin/sh
CLOJURE_DIR=/home/bbrown/src/clojure/clojure
CLOJURE_JAR=$CLOJURE_DIR/target/clojure-lang-1.0-SNAPSHOT.jar
if [ -z "$1" ]; then 
	java -cp $CLOJURE_DIR/jline-0.9.94.jar:$CLOJURE_JAR \
            jline.ConsoleRunner clojure.lang.Repl    
else
	java -cp $CLOJURE_JAR clojure.lang.Script $1
fi
